### ISSUE TITLE
sudo pm2 endpoints shows error

### ISSUE THREAD

**Issue by Rafi993** [firstopinion/endpoints#53]
endpoints dosent start and shows error when tried to start with pm2 in linux 
I tried following the instructions given [here](https://github.com/firstopinion/endpoints/issues/51)

`sudo pm2 start endpoints -- --prefix=index --host=localhost:2002`

**Comment by Jaymon** [comment]
Can you include the error message? It would help with diagnosing the problem

**Comment by Rafi993** [comment]
when run **sudo pm2** show it gives the following status
│ status            │ errored                                                   
│ name              │ endpoints                                                                   
│ restarts          │ 15                                                                                           
│ uptime            │ 0                                                                                            
│ script path       │ /usr/local/bin/endpoints                                                       
│ script args       │ --prefix=index --host=localhost:2002 --interpreter=python 
│ error log path    │ /home/ubuntu/.pm2/logs/endpoints-error-1.log          
│ out log path      │ /home/ubuntu/.pm2/logs/endpoints-out-1.log             
│ pid path          │ /home/ubuntu/.pm2/pids/endpoints-1.pid                      
│ interpreter       │ node                                                                                 
│ interpreter args  │ N/A                                                                                 
│ script id         │ 1                                                                                           
│ exec cwd          │ /home/ubuntu/brand_marshal/testendpoint                   
│ exec mode         │ fork_mode                                                                       
│ node.js version   │ 4.4.7                                                                                
│ watch & reload    │ ✘                                                                                   
│ unstable restarts │ 0                                                                                     
│ created at        │ N/A                                                                                    

when I tried to run curl **http://localhost:2002** it gives the following error
   curl: (7) Failed to connect to localhost port 2002: Connection refused

the the file /home/ubuntu/.pm2/logs/endpoints-error-1.log gives the following error

```
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
    at Module._compile (module.js:409:26)
"~/.pm2/logs/endpoints-error-1.log" [readonly] 880L, 46720C                                           
```

**Comment by Jaymon** [comment]
It looks like you are passing into endpoints these arguments: 

    --prefix=index --host=localhost:2002 --interpreter=python

But endpoints doesn't have an `--interpreter` flag, you can see this by running `endpoints --help`

```
usage: endpoints [-h] [-v] [--quiet] --prefix PREFIX [--file FILE] --host HOST
                [--count COUNT] [--dir DIRECTORY]
```

however, pm2 does have an `--interpreter` flag and might need it? My best guess is pm2 is failing before actually getting to the endpoints call.

I would double check your pm2 configuration and go from there.
